Update Lab03

diff --git a/lab03/1/1_1/Makefile b/lab03/1/1_1/Makefile
--- a/lab03/1/1_1/Makefile
+++ b/lab03/1/1_1/Makefile
@@ -1,5 +1,14 @@
+CC = gcc
+CFLAGS = -pthread
+SRC = 1_1.c
+OUT = 1.out
+OUTPUT = 1.txt
+ANSWER = 1_ans.txt
+
+.DEFAULT_GOAL := my-judge
+
 judge:
-	@gcc -o 1.out 1_1.c
+	@$(CC) $(CFLAGS) $(SRC) -o $(OUT)
 	@i=1; while [ $$i -le 100 ]; do \
 		./1.out; \
 		i=$$((i + 1)); \
@@ -8,12 +17,31 @@ judge:
 	@rm -f 1.out
 	@rm -f 1.txt
 
-diff:
-	@gcc -o 1.out 1.c
+my-judge:
+# remove 1.txt if it exists
+# if check the difference between 1_ans.txt and 1.txt, if there is no difference, then print Success, otherwise print Failed
+	@$(CC) $(CFLAGS) $(SRC) -o $(OUT)
+	@if [ -f $(OUTPUT) ]; then \
+		rm -f $(OUTPUT); \
+	fi
 	@i=1; while [ $$i -le 100 ]; do \
-		./1.out; \
+		./$(OUT); \
 		i=$$((i + 1)); \
 	done
-	@git diff --word-diff  1_ans.txt 1.txt || true
-	@rm -f 1.out
-	@rm -f 1.txt
+	@if diff $(ANSWER) $(OUTPUT) > /dev/null; then \
+		echo "Success"; \
+	else \
+		echo "Failed"; \
+	fi
+	@rm -f $(OUT)
+	@rm -f $(OUTPUT)
+
+diff:
+	@$(CC) $(CFLAGS) $(SRC) -o $(OUT)
+	@i=1; while [ $$i -le 100 ]; do \
+		./$(OUT); \
+		i=$$((i + 1)); \
+	done
+	@git diff --word-diff $(ANSWER) $(OUTPUT) || true
+	@rm -f $(OUT)
+	@rm -f $(OUTPUT)
diff --git a/lab03/2/Makefile b/lab03/2/Makefile
--- a/lab03/2/Makefile
+++ b/lab03/2/Makefile
@@ -1,12 +1,48 @@
+CC = gcc
+CFLAGS = -pthread
+SRC1 = 2_1.c
+SRC2 = 2_2.c
+OUT = 2.out
+OUTPUT = 2.txt
+ANSWER1 = 2_1_ans.txt
+ANSWER2 = 2_2_ans.txt
+
+my-judge1:
+	@$(CC) $(CFLAGS) $(SRC1) -o $(OUT)
+	@rm -f $(OUTPUT)
+	@./$(OUT)
+	@if diff $(ANSWER1) $(OUTPUT) > /dev/null; then \
+		echo "Success"; \
+	else \
+		echo "Failed"; \
+	fi
+	@rm -f $(OUT)
+	@rm -f $(OUTPUT)
+
+my-judge2:
+	@$(CC) $(CFLAGS) $(SRC2) -o $(OUT)
+	@rm -f $(OUTPUT)
+	@i=1; while [ $$i -le 10 ]; do \
+		./$(OUT); \
+		i=$$((i + 1)); \
+	done
+	@if diff $(ANSWER2) $(OUTPUT) > /dev/null; then \
+		echo "Success"; \
+	else \
+		echo "Failed"; \
+	fi
+	@rm -f $(OUT)
+	@rm -f $(OUTPUT)
+
 judge1:
-	@gcc -o 2.out 2_1.c
+	$(CC) $(CFLAGS) $(SRC1) -o $(OUT)
 	@./2.out
 	@./judge.out 1
 	@rm -f 2.out
 	@rm -f 2.txt
 
 judge2:
-	@gcc -o 2.out 2_2.c
+	$(CC) $(CFLAGS) $(SRC2) -o $(OUT)
 	@i=1; while [ $$i -le 10 ]; do \
 		./2.out; \
 		i=$$((i + 1)); \
@@ -15,9 +51,26 @@ judge2:
 	@rm -f 2.out
 	@rm -f 2.txt
 
-diff:
-	@gcc -o 2.out 2_1.c
-	@./2.out
-	@git diff --word-diff  2_ans.txt 2.txt || true
-	@rm -f 2.out
-	@rm -f 2.txt
+diff1:
+	@$(CC) $(CFLAGS) $(SRC1) -o $(OUT)
+	@rm -f $(OUTPUT)
+	@./$(OUT)
+	@git diff --word-diff $(ANSWER1) $(OUTPUT) || true
+	@rm -f $(OUT)
+	@rm -f $(OUTPUT)
+
+diff2:
+	@$(CC) $(CFLAGS) $(SRC2) -o $(OUT)
+	@rm -f $(OUTPUT)
+	@i=1; while [ $$i -le 10 ]; do \
+		./$(OUT); \
+		i=$$((i + 1)); \
+	done
+	@git diff --word-diff $(ANSWER2) $(OUTPUT) || true
+	@rm -f $(OUT)
+	@rm -f $(OUTPUT)
+
+clean:
+	if [ -f 2.out ]; then \
+		rm -f 2.out; \
+	fi
